"""Add cascade delete to rating_history relationship

Revision ID: 733a3a4ee3db
Revises: 53882e95da98
Create Date: 2024-11-22 14:45:58.944962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733a3a4ee3db'
down_revision: Union[str, None] = '53882e95da98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
