name: Docker Compose and API Tests

on:
  push:
    branches:
      - api_tests

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Debug Docker
        run: |
          docker info
          docker ps

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r tests/requirements.txt

      - name: Copy .env file to the working directory
        run: cp .env /home/runner/work/acc-model-app/acc-model-app/.env

      - name: Start Docker Compose
        run: docker compose up --build -d

      - name: Debug Docker
        run: |
          docker info
          docker ps

      - name: Wait for backend to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://127.0.0.1:8000/health; then
              echo "Backend is ready"
              break
            fi
            echo "Waiting for backend..."
            sleep 5
          done
          curl -s http://127.0.0.1:8000/health || exit 1

      - name: Run API Tests
        run: python -m pytest tests/tests/test_end_to_end_api_test.py

      - name: Shut down Docker Compose
        run: docker-compose down
