on:
  push:
    branches: [docker-compose-api-tests-workflow]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose jq

      - name: Set Environment Variables
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "NEW_DB_USER=${{ secrets.NEW_DB_USER }}" >> .env
          echo "NEW_DB_PASSWORD=${{ secrets.NEW_DB_PASSWORD }}" >> .env
          echo "NEW_DB_NAME=${{ secrets.NEW_DB_NAME }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env

      - name: Build and Start Services
        run: |
          docker-compose up --build -d

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            if docker exec acc-model-app_database_1 pg_isready -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }}; then
              echo "PostgreSQL is ready"
              break
            fi
            echo "Waiting for PostgreSQL..."
            sleep 5
          done
          docker exec acc-model-app_database_1 pg_isready -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }} || exit 1

      - name: Create a New User and Database in PostgreSQL
        run: |
          docker exec -i acc-model-app_database_1 psql -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }} <<EOF
          CREATE USER ${{ secrets.NEW_DB_USER }} WITH PASSWORD '${{ secrets.NEW_DB_PASSWORD }}';
          CREATE DATABASE ${{ secrets.NEW_DB_NAME }} WITH OWNER ${{ secrets.NEW_DB_USER }};
          GRANT ALL PRIVILEGES ON DATABASE ${{ secrets.NEW_DB_NAME }} TO ${{ secrets.NEW_DB_USER }};
          EOF

      - name: Wait for backend to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://127.0.0.1:8000/health; then
              echo "Backend is ready"
              break
            fi
            echo "Waiting for backend..."
            sleep 5
          done
          curl -s http://127.0.0.1:8000/health || exit 1

      - name: Create User in Backend
        run: |
          USER_RESPONSE=$(curl -s -X 'POST' \
            'http://localhost:8000/users/' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -d '{
              "username": "username08",
              "email": "user08@qxf2.com",
              "designation": "QA",
              "password": "password08"
            }')

          echo "User created: $USER_RESPONSE"

      - name: Verify PostgreSQL Users and Databases (Optional)
        run: |
          docker exec -i acc-model-app_database_1 psql -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }} -c "\du"
          docker exec -i acc-model-app_database_1 psql -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }} -c "\l"

      - name: Fetch Bearer Token
        id: get_token
        run: |
          BEARER_TOKEN_RESPONSE=$(curl -s -X 'POST' \
            'http://localhost:8000/token' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/x-www-form-urlencoded' \
            -d 'username=username08&password=password08')

          echo "Bearer Token: $BEARER_TOKEN_RESPONSE"
          BEARER_TOKEN=$(echo "$BEARER_TOKEN_RESPONSE" | jq -r '.access_token')

          # Export BEARER_TOKEN as an environment variable directly
          echo "::set-env name=bearer_token::$BEARER_TOKEN"

      - name: Run API Tests Inside Container
        run: |
          pip install -r tests/requirements.txt
          pytest tests/tests/test_end_to_end_api_test.py -s -v
      
      - name: Debug Docker
        run: |
          docker info
          docker ps

      - name: Stop and remove services
        run: |
          docker-compose down
